#!/usr/bin/env bash

export PATH="/usr/local/sbin:/usr/local/bin:$PATH"


# Version Managers
if [ "$PYENV_ROOT" ]; then
    export PATH="$PYENV_ROOT/bin:$PATH";
fi;

if [ "$RBENV_ROOT" ]; then
    export PATH="$RBENV_ROOT/bin:$PATH";
fi;
