[aliases.common]
# List files with more information
#   -l    List files in the long format
#   -h    When used with the -l option, use unit suffixes: Byte, Kilobyte, Megabyte, Gigabyte, etc
#   -F    Suffix paths: directories /, executables *, symbolic links @, sockets =, whiteouts %, FIFOs |
#   -G    Enable colorized output
ll = 'ls -lhFG'
la = 'ls -lhaFG'
ls = 'command ls -G'

# Grep with colours
grep = 'grep --color=auto'
fgrep = 'fgrep --color=auto'
egrep = 'egrep --color=auto'

# Git
g = 'git'
ga = 'git add'
gaa = 'git add .'
gc = 'git commit'
gcm = 'git commit -m'
gd = 'git diff'
gds = 'git diff --staged'
gl = 'git log --pretty=oneline -n 20 --graph --abbrev-commit'
gll = 'git log'
gph = 'git push'
gpl = 'git pull'
gs = 'git status -s'
gss = 'git status'
gsw = 'git switch'

[aliases.personal]

[aliases.work]
dd = '~/Work/dashdoc/dd.py'
