[packages.darwin.taps]
common = []
personal = []
work = []

[packages.darwin.brews]
common = ["bat", "coreutils", "mise", "ripgrep", "starship", "vim"]
personal = ["exiftool", "golangci-lint"]
work = [
	"cloud-sql-proxy",
	# TODO: Add a way to setup paths per machine
	# Needed exports after installing libpq
	# 	export PATH="/opt/homebrew/opt/libpq/bin:$PATH"
	# 	export PKG_CONFIG_PATH="/opt/homebrew/opt/libpq/lib/pkgconfig"
	# 	export LDFLAGS="-L/opt/homebrew/opt/libpq/lib"
	# 	export CPPFLAGS="-I/opt/homebrew/opt/libpq/include"
	"libpq",      # Needed for building psycopg2 (python pip)
	"libxml2",    # Needed for building xmlsec (python pip)
	"libxmlsec1", # Needed for building xmlsec (python pip)
	"pkg-config", # Needed for building xmlsec (python pip)
]

[packages.darwin.casks]
common = [
	"1password",
	"docker",
	"firefox",
	"font-fira-code-nerd-font",
	"font-victor-mono-nerd-font",
	"google-chrome",
	"iterm2",
	"raycast",
	"slack",
	"spotify",
	"visual-studio-code",
]
personal = [
	"android-file-transfer",
	"appcleaner",
	"dropbox",
	"gimp",
	"obsidian",
	"telegram",
	"vlc",
]
work = [
	"android-studio",
	"google-cloud-sdk",
	"linear-linear",
	"notion",
	"zulu@17",
]
